version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - goconst
    - gocyclo
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
  settings:
    staticcheck:
      # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
      # Default: ["*"]
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
